---
- name: "update local apt repo."
  become: true
  apt:
    update_cache: yes

- name: "upgrade apt packages"
  become: true
  apt:
    upgrade: yes

- name: "Remove Stale dependencies"
  become: true
  apt:
    autoremove: yes

- name: "Install dependencies (nodejs & npm)"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2"
  become: true
  apt:
    name: pm2
    update_cache: yes
    state: present